<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="topictype" content="Uc" />
<meta name="devlang" content="idl" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdFeaNumbering.CATScript</title>
</head>

<body onload="highlightSearchTerms();">
<script type="text/javascript">insertCopyright();</script>

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------</span>
<span class="comment">'This sample creates nodes and elements numbering specifications.</span>

<span class="comment">'Steps:</span>
<span class="comment">'    1- Retrieves the active editor</span>
<span class="comment">'    2- Retrieves the root product</span>
<span class="comment">'    3- Retrieves the assembly FEM Rep</span>
<span class="comment">'    4- Creates global numbering specifications</span>
<span class="comment">'    5- Creates a link between the assembly FEM and the first occurrence FEM</span>
<span class="comment">'    6- Sets numbering offsets</span>
<span class="comment">'    7- Retrieves the mesh part of the first occurence FEM</span>
<span class="comment">'    8- Creates mesh part numbering specifications</span>
<span class="comment">'    9- Retrieves the group of the first occurence FEM</span>
<span class="comment">'    10- Creates group numbering specifications</span>
<span class="comment">'    11- Updates the assembly FEM Rep</span>

<span class="keyword">Sub</span> CATMain()

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 1- Retrieves the active editor</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyEditor <span class="keyword">As</span> Editor
<span class="keyword">Set</span> MyEditor = CATIA.ActiveEditor

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 2- Retrieves the root product</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyRootOcc <span class="keyword">As</span> VPMRootOccurrence
<span class="keyword">Set</span> MyRootOcc = MyEditor.ActiveObject

<span class="keyword">Dim</span> MyRootProduct <span class="keyword">As</span> VPMReference
<span class="keyword">Set</span> MyRootProduct = MyRootOcc.PLMEntity

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 3- Retrieves the assembly FEM Rep</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyProductService <span class="keyword">As</span> PLMProductService
<span class="keyword">Set</span> MyProductService = MyEditor.GetService(&quot;PLMProductService&quot;)

<span class="keyword">Dim</span> MyFEMRoot <span class="keyword">As</span> SimFemRoot
<span class="keyword">For Each</span> MyEntity <span class="keyword">In</span> MyProductService.EditedContent
  <span class="keyword">Dim</span> MyRef <span class="keyword">As</span> VPMReference
  <span class="keyword">Set</span> MyRef = MyEntity

  <span class="keyword">Dim</span> MyReps <span class="keyword">As</span> VPMRepInstances
  <span class="keyword">Set</span> MyReps = MyRef.RepInstances

  <span class="keyword">For Each</span> MyRep <span class="keyword">In</span> MyReps
    <span class="keyword">Dim</span> MyRepRef <span class="keyword">As</span> VPMRepReference
    <span class="keyword">Set</span> MyRepRef = MyRep.ReferenceInstanceOf
    <span class="keyword">Dim</span> attr <span class="keyword">As</span> <span class="keyword">String</span>
    attr = MyRepRef.GetAttributeValue(&quot;V_discipline&quot;)

    <span class="keyword">If</span> (attr = &quot;FEM&quot;) <span class="keyword">Then</span>
      <span class="keyword">Set</span> MyFEMRoot = MyRepRef.GetItem(&quot;SimFemRoot&quot;)
    <span class="keyword">End If</span>
  <span class="keyword">Next</span>
<span class="keyword">Next</span>

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 4- Creates global numbering specifications</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyNumberingEntity <span class="keyword">As</span> SimNumbering
<span class="keyword">Set</span> MyNumberingEntity = MyFEMRoot.GetItem(&quot;SimNumbering&quot;)
MyNumberingEntity.SetAttributeValue &quot;NodesLowerBoundValue&quot;, 1
MyNumberingEntity.SetAttributeValue &quot;NodesUpperBoundValue&quot;, 1000000
MyNumberingEntity.SetAttributeValue &quot;ElementsLowerBoundValue&quot;, 1
MyNumberingEntity.SetAttributeValue &quot;ElementsUpperBoundValue&quot;, 2000000

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 5- Creates a link between the assembly FEM and the first occurrence FEM</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyRootOccurrences <span class="keyword">As</span> VPMOccurrences
<span class="keyword">Set</span> MyRootOccurrences = MyRootOcc.Occurrences
<span class="keyword">Dim</span> MyOccurrence <span class="keyword">As</span> VPMOccurrence
<span class="keyword">Set</span> MyOccurrence = MyRootOccurrences.Item(1)

<span class="keyword">Dim</span> MyRepInstances <span class="keyword">As</span> VPMRepInstances
<span class="keyword">Set</span> MyRepInstances = MyOccurrence.InstanceOccurrenceOf.ReferenceInstanceOf.RepInstances

<span class="keyword">Dim</span> MyFirstFEMRoot <span class="keyword">As</span> SimFemRoot
<span class="keyword">Dim</span> MyFirstLink <span class="keyword">As</span> AnyObject
<span class="keyword">For Each</span> MyRep <span class="keyword">In</span> MyRepInstances
  <span class="keyword">Set</span> MyRepRef = MyRep.ReferenceInstanceOf
  attr = MyRepRef.GetAttributeValue(&quot;V_discipline&quot;)
  <span class="keyword">If</span> (attr = &quot;FEM&quot;) <span class="keyword">Then</span>
    <span class="keyword">Set</span> MyFirstFEMRoot = MyRepRef.GetItem(&quot;SimFemRoot&quot;)
    <span class="keyword">Set</span> MyFirstLink = MyProductService.ComposeLink(MyOccurrence, MyRep, <span class="keyword">Nothing</span>)
  <span class="keyword">End If</span>
<span class="keyword">Next</span>

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 6- Sets numbering offsets</span>
<span class="comment">'--------------------------------------------------------------------------</span>
MyFEMRoot.SetNumberingOffsetValue &quot;nodes&quot;, MyFirstLink, 500000
MyFEMRoot.SetNumberingOffsetValue &quot;elements&quot;, MyFirstLink, 600000

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 7- Retrieves the mesh part of the first occurence FEM</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyMeshSet <span class="keyword">As</span> SimMeshSet
<span class="keyword">Set</span> MyMeshSet = MyFirstFEMRoot.GetSet(&quot;SimNodesElements&quot;)
<span class="keyword">Dim</span> MyMeshParts <span class="keyword">As</span> SimMeshParts
<span class="keyword">Set</span> MyMeshParts = MyMeshSet.MeshParts
<span class="keyword">Dim</span> MyMeshPart <span class="keyword">As</span> SimMeshPart
<span class="keyword">Set</span> MyMeshPart = MyMeshParts.Item(1)

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 8- Creates mesh part numbering specifications</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Set</span> MyNumberingEntity = MyMeshPart.GetItem(&quot;SimNumbering&quot;)
MyNumberingEntity.SetAttributeValue &quot;NodesLowerBoundValue&quot;, 100001
MyNumberingEntity.SetAttributeValue &quot;NodesUpperBoundValue&quot;, 102000
MyNumberingEntity.SetAttributeValue &quot;ElementsLowerBoundValue&quot;, 103001
MyNumberingEntity.SetAttributeValue &quot;ElementsUpperBoundValue&quot;, 105000

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 9- Retrieves the group of the first occurence FEM</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyGroups <span class="keyword">As</span> SimGroups
<span class="keyword">Set</span> MyGroups = MyFirstFEMRoot.GetSet(&quot;SimGroups&quot;)
<span class="keyword">Dim</span> MyGroup <span class="keyword">As</span> SimGroup
<span class="keyword">Set</span> MyGroup = MyGroups.Item(1)

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 10- Creates group numbering specifications</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Set</span> MyNumberingEntity = MyGroup.GetItem(&quot;SimNumbering&quot;)
MyNumberingEntity.SetAttributeValue &quot;NodesLowerBoundValue&quot;, 105101
MyNumberingEntity.SetAttributeValue &quot;NodesUpperBoundValue&quot;, 105200

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 11- Updates the assembly FEM Rep</span>
<span class="comment">'--------------------------------------------------------------------------</span>
MyFEMRoot.Update

<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>
  </body>
</html>
