<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="topictype" content="Uc" />
<meta name="devlang" content="idl" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdMpaLinkAccess.CATScript</title>
</head>

<body onload="highlightSearchTerms();">
<script type="text/javascript">insertCopyright();</script>


<pre class=>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------</span>
<span class="comment">'This sample define and manage simulation feature supports.</span>

<span class="comment">'Steps:</span>
<span class="comment">'          1- Retrieving the active Product 										</span>
<span class="comment">'          2- Creating the FEM Rep and retrieving its Rep Manager 								</span>
<span class="comment">'          3- Creating sections								</span>
<span class="comment">'          4- Setting the meshed bolt support from publication					</span>
<span class="comment">'          5- Setting the shell section supports from product structure									</span>
<span class="comment">'          6- Replacing the first shell section support							</span>
<span class="comment">'          7- Removing all supports of the shell section										</span>
<span class="comment">'============================================================================================</span>

<span class="keyword">Sub </span>CATMain()
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 1- Retrieving the active Product</span>
    <span class="comment">'=====================================================================</span>
    
<span class="keyword">	Dim </span>myEditor<span class="keyword"> As </span>Editor
<span class="keyword">	Set </span>myEditor = CATIA.ActiveEditor
	
<span class="keyword">	Dim </span>myProdService<span class="keyword"> As </span>PLMProductService
<span class="keyword">	Set </span>myProdService = myEditor.GetService(&quot;PLMProductService&quot;)
	
<span class="keyword">	Dim </span>myEntities<span class="keyword"> As </span>PLMEntities
<span class="keyword">	Set </span>myEntities = myProdService.EditedContent
	
<span class="keyword">	Dim </span>myModel<span class="keyword"> As </span>VPMReference
<span class="keyword">	Set </span>myModel = myEntities.Item(1)
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 2- Creating the FEM Rep and retrieving its Rep Manager</span>
    <span class="comment">'=====================================================================</span>
	
<span class="keyword">	Dim </span>myPrdRepFactory<span class="keyword"> As </span>SimPrdRepFactory
<span class="keyword">	Set </span>myPrdRepFactory =myModel.GetItem(&quot;SimPrdRepFactory&quot;)
	
<span class="keyword">	Dim </span>myRepRef<span class="keyword"> As </span>VPMRepReference
<span class="keyword">	Set </span>myRepRef = myPrdRepFactory.CreatePrdRep(&quot;FEM&quot;)
	
<span class="keyword">	Dim </span>myFEMRoot<span class="keyword"> As </span>SimFemRoot
<span class="keyword">	Set </span>myFEMRoot = myRepRef.GetItem(&quot;SimFemRoot&quot;)
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 3- Creating sections</span>
    <span class="comment">'=====================================================================</span>
	
<span class="comment">	'Retrieving the Property Set</span>
	
<span class="keyword">	Dim </span>myPropertiesSet<span class="keyword"> As </span>SimProperties
<span class="keyword">	Set </span>myPropertiesSet = myFEMRoot.GetSet(&quot;SimProperties&quot;)
	
<span class="comment">	'Creating the Properties</span>
	
<span class="keyword">	Dim </span>myShellSection<span class="keyword"> As </span>SimShellSection
<span class="keyword">	Set </span>myShellSection = myPropertiesSet.Add(&quot;SimShellSection&quot;)
	
<span class="keyword">	Dim </span>myMeshedBolt<span class="keyword"> As </span>SimMeshedBolt
<span class="keyword">	Set </span>myMeshedBolt = myPropertiesSet.Add(&quot;SimMeshedBolt&quot;)
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 4- Setting the meshed bolt support from publication</span>
    <span class="comment">'=====================================================================</span>
	
<span class="comment">	'Retrieving the publication</span>
	
<span class="keyword">	Dim </span>myPublications <span class="keyword"> As </span>VPMPublications
<span class="keyword">	Set </span>myPublications  = myModel.Publications
	
<span class="keyword">	Dim </span>mySupport<span class="keyword"> As </span>VPMPublication
<span class="keyword">	Set </span>mySupport = myPublications.GetItem(&quot;Bolt-1&quot;)
	
<span class="comment">	'Setting the meshed bolt support</span>
	
<span class="keyword">	Dim </span>myLinkAccess<span class="keyword"> As </span>SimLinkAccess
<span class="keyword">	Set </span>myLinkAccess = myMeshedBolt.GetItem(&quot;SimLinkAccess&quot;)
	
	myLinkAccess.AddLink &quot;MainSupport&quot;, mySupport
	
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 5- Setting the shell section supports from product structure</span>
    <span class="comment">'=====================================================================</span>
	
<span class="comment">	'Retrieving the ws3_bolt_part.2 part occurrence</span>
	
<span class="keyword">	Dim </span>myRootOccurrence<span class="keyword"> As </span>VPMRootOccurrence
<span class="keyword">	Set </span>myRootOccurrence = myProdService.RootOccurrence
	
<span class="keyword">	Dim </span>myPartOccurrence<span class="keyword"> As </span>PLMOccurrence
<span class="keyword">	For </span>i = 1<span class="keyword"> to </span>myRootOccurrence.Occurrences.Count
	<span class="keyword">	If </span>myRootOccurrence.Occurrences.Item(i).Name = "ws3_bolt_part.2"<span class="keyword"> Then</span>
		<span class="keyword">	Set </span>myPartOccurrence = myRootOccurrence.Occurrences.Item(i)
	<span class="keyword">	End If</span>
<span class="keyword">	Next</span>
	
<span class="comment">	'Retrieving the ws3_bolt_part.2 part rep instance</span>
	
<span class="keyword">	Dim </span>myPartInstance<span class="keyword"> As </span>VPMInstance
<span class="keyword">	Set </span>myPartInstance = myPartOccurrence.InstanceOccurrenceOf
	
<span class="keyword">	Dim </span>myPartInstanceRef<span class="keyword"> As </span>VPMReference
<span class="keyword">	Set </span>myPartInstanceRef = myPartInstance.ReferenceInstanceOf
	
<span class="keyword">	Dim </span>myPartRepInstance<span class="keyword"> As </span>VPMRepInstance
<span class="keyword">	Set </span>myPartRepInstance = myPartInstanceRef.RepInstances.Item(1)
	
<span class="comment">	'Retrieving the ws3_bolt_part.2 part body</span>
	
<span class="keyword">	Dim </span>myPartRepInstanceRef<span class="keyword"> As </span>VPMRepReference
<span class="keyword">	Set </span>myPartRepInstanceRef = myPartRepInstance.ReferenceInstanceOf
	
<span class="keyword">	Dim </span>myPart<span class="keyword"> As </span>Part
<span class="keyword">	Set </span>myPart = myPartRepInstanceRef.GetItem(&quot;Part&quot;)
	
<span class="keyword">	Dim </span>myPartBody<span class="keyword"> As </span>Body
<span class="keyword">	Set </span>myPartBody = myPart.MainBody
	
<span class="comment">	'Composing link to the ws3_bolt_part.2 part body</span>
	
<span class="keyword">	Dim </span>myReference<span class="keyword"> As </span>Reference
<span class="keyword">	Set </span>myReference = myPart.CreateReferenceFromObject(myPartBody)
	
<span class="keyword">	Dim </span>myLinkToFirstSupport<span class="keyword"> As </span>AnyObject
<span class="keyword">	Set </span>myLinkToFirstSupport = myProdService.ComposeLink(myPartOccurrence, myPartRepInstance, myReference)
	
<span class="comment">	'Setting the shell section first support</span>
	
<span class="keyword">	Set </span>myLinkAccess = myShellSection.GetItem(&quot;SimLinkAccess&quot;)
	
	myLinkAccess.AddLink &quot;MainSupport&quot;, myLinkToFirstSupport
	
<span class="comment">	'Retrieving the ws3_bolt_part.3 part occurrence</span>
	
<span class="keyword">	For </span>i = 1<span class="keyword"> to </span>myRootOccurrence.Occurrences.Count
	<span class="keyword">	If </span>myRootOccurrence.Occurrences.Item(i).Name = "ws3_bolt_part.3"<span class="keyword"> Then</span>
		<span class="keyword">	Set </span>myPartOccurrence = myRootOccurrence.Occurrences.Item(i)
	<span class="keyword">	End If</span>
<span class="keyword">	Next</span>
	
<span class="comment">	'Retrieving the ws3_bolt_part.3 part rep instance</span>
	
<span class="keyword">	Set </span>myPartInstance = myPartOccurrence.InstanceOccurrenceOf
	
<span class="keyword">	Set </span>myPartInstanceRef = myPartInstance.ReferenceInstanceOf
	
<span class="keyword">	Set </span>myPartRepInstance = myPartInstanceRef.RepInstances.Item(1)
	
<span class="comment">	'Retrieving the ws3_bolt_part.3 part body</span>
	
<span class="keyword">	Set </span>myPartRepInstanceRef = myPartRepInstance.ReferenceInstanceOf
	
<span class="keyword">	Set </span>myPart = myPartRepInstanceRef.GetItem(&quot;Part&quot;)
	
<span class="keyword">	Set </span>myPartBody = myPart.MainBody
	
<span class="comment">	'Composing link to the ws3_bolt_part.3 part body</span>
	
<span class="keyword">	Set </span>myReference = myPart.CreateReferenceFromObject(myPartBody)
	
<span class="keyword">	Dim </span>myLinkToSecondSupport<span class="keyword"> As </span>AnyObject
<span class="keyword">	Set </span>myLinkToSecondSupport = myProdService.ComposeLink(myPartOccurrence, myPartRepInstance, myReference)
	
<span class="comment">	'Setting the shell section second support</span>
	
	myLinkAccess.AddLink &quot;MainSupport&quot;, myLinkToSecondSupport
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 6- Replacing the first shell section support</span>
    <span class="comment">'=====================================================================</span>
	
<span class="comment">	'Retrieving the publication</span>
	
<span class="keyword">	Dim </span>myNewSupport<span class="keyword"> As </span>VPMPublication
<span class="keyword">	Set </span>myNewSupport = myPublications.GetItem(&quot;Pipe&quot;)
	
<span class="comment">	'Removing first support</span>
	
	myLinkAccess.RemoveLink &quot;MainSupport&quot;, myLinkToFirstSupport
	
<span class="comment">	'Setting the new support</span>
	
	myLinkAccess.AddLink &quot;MainSupport&quot;, myNewSupport
	
    <span class="comment">'=====================================================================</span>
    <span class="comment">' 7- Removing all supports of the shell section</span>
    <span class="comment">'=====================================================================</span>
	
	myLinkAccess.RemoveAllLinks &quot;MainSupport&quot;
	
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
