<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="topictype" content="Uc" />
<meta name="devlang" content="idl" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdUcCreatePlotLegend.CATScript</title>
</head>

<body onload="highlightSearchTerms();">
<script type="text/javascript">insertCopyright();</script>
    '--------------------------------------------------------------------------
<pre>
<span class="comment">'---------------------------- Sample MACRO written in Basic Script ---------------------------------</span>
<span class="comment">'This sample creates and manages the plot legend.</span>

<span class="comment">'Steps:</span>
<span class="comment">'    1- Opens the simulation document and retrieves the results manager</span>
<span class="comment">'    2- Retrieves the results analysis case</span>
<span class="comment">'    3- Creates the field plot through template</span>
<span class="comment">'    4- Retrieves the legend from the plot</span>
<span class="comment">'    5- Gets and sets the minimum and maximum value for the legend</span>
<span class="comment">'    6- Gets and Sets the color modifiers</span> 
<span class="comment">'    7- Gets and Sets the legend style</span> 
<span class="comment">'    8- Gets and sets the number of legend colors</span>
<span class="comment">'    9- Sets the number format</span>
<span class="comment">'    10-Specifies the animation range</span>

<span class="keyword">Sub </span>CATMain()

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    1- Opens the simulation document and retrieves the results manager</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>oEditor<span class="keyword"> As </span>Editor
<span class="keyword">Set </span>oEditor = CATIA.ActiveEditor

<span class="keyword">Dim </span>oProdService<span class="keyword"> As </span>PLMProductService
<span class="keyword">Set </span>oProdService = oEditor.GetService("PLMProductService")

<span class="keyword">Dim </span>oEntities<span class="keyword"> As </span>PLMEntities

<span class="keyword">If Not </span>oProdService.EditedContent<span class="keyword"> Is Nothing Then</span>

<span class="keyword">Set </span>oEntities = oProdService.EditedContent

<span class="keyword">Dim </span>oEntity<span class="keyword"> As </span>PLMEntity
<span class="keyword">Dim </span>oSimObjEntity<span class="keyword"> As </span>PLMEntity

<span class="keyword">For </span>Each oEntity<span class="keyword"> In </span>oEntities
    <span class="keyword">If </span>oEntity.GetCustomType = "SIMObjSimulationObjectGenericDS" Or oEntity.GetCustomType = "DesignSight"<span class="keyword"> Then </span>
        <span class="keyword">Set </span>oSimObjEntity = oEntity
    <span class="keyword">End If</span>
<span class="keyword">Next</span>

<span class="keyword">Dim </span>oSimulationRoot<span class="keyword"> As </span>SimulationReference
<span class="keyword">Set </span>oSimulationRoot = oSimObjEntity
    
<span class="keyword">Dim </span>oResults<span class="keyword"> As </span>SimulationResults
<span class="keyword">Set </span>oResults = oSimulationRoot.Results

<span class="keyword">Dim </span>oSimulationRepRes<span class="keyword"> As </span>SimulationRepresentation
<span class="keyword">Set </span>oSimulationRepRes = oResults.Item(1)  

<span class="keyword">Dim </span>oRootRepRes<span class="keyword"> As </span>SimResultRepManager
<span class="keyword">Set </span>oRootRepRes = oSimulationRepRes.Root    

<span class="keyword">Dim </span>oResultsManager<span class="keyword"> As </span>SimResultsManager
<span class="keyword">Set </span>oResultsManager = oRootRepRes.GetItem("SimResultsManager")   

<span class="keyword">End If</span>


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    2- Retrieves the results analysis case</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>oResultsAnalysisCases<span class="keyword"> As </span>SimResultsAnalysisCases
<span class="keyword">Set </span>oResultsAnalysisCases = oResultsManager.ResultsAnalysisCases

<span class="keyword">Dim </span>oResultsAnalysisCase<span class="keyword"> As </span>SimResultsAnalysisCase
<span class="keyword">Set </span>oResultsAnalysisCase = oResultsAnalysisCases.Item(1)


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    3- Creates the field plot through template</span>
<span class="comment">'--------------------------------------------------------------------------</span>
    
<span class="keyword">Dim </span>sId<span class="keyword"> As </span>String
sId = "Contour_Stress_Tresca"
<span class="keyword">Dim </span>oPlot<span class="keyword"> As </span>SimFieldPlot
<span class="keyword">Set </span>oPlot = oResultsAnalysisCase.CreateFieldPlotByID(sId, True)


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    4- Retrieves the legend form the plot</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>oPlotLegend<span class="keyword"> As </span>SimLegend
<span class="keyword">Set </span>oPlotLegend = oPlot.Legend


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    5- Gets and sets the minimum and maximum value for the legend</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>nbMinvalue<span class="keyword"> As </span>double
<span class="keyword">Dim </span>nbMaxvalue<span class="keyword"> As </span>double

oPlotLegend.GetMinMaxValue nbMinvalue, nbMaxvalue, True, False
oPlotLegend.SetMinMaxValue 100, 10000, True


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    6- Gets and Sets the color modifiers</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>bSmooth<span class="keyword"> As </span>boolean
<span class="keyword">Dim </span>bInverse<span class="keyword"> As </span>boolean

oPlotLegend.GetColorModifiers bSmooth, bInverse
oPlotLegend.SetColorModifiers True, True


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    7- Gets and Sets the legend style</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>sStyle<span class="keyword"> As </span>String

sStyle = oPlotLegend.Style 
oPlotLegend.Style = "SMAMpaLegendStyle_Detailed"


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    8- Gets and sets the number of legend colors</span>
<span class="comment">'--------------------------------------------------------------------------</span>

<span class="keyword">Dim </span>nbColors<span class="keyword"> As </span>Long
nbColors = oPlotLegend.NbColors
oPlotLegend.NbColors = nbColors * 2


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    9- Sets the number format</span>
<span class="comment">'--------------------------------------------------------------------------</span>

oPlotLegend.NumberFormat = 1


<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">'    10-Specifies the animation range</span>
<span class="comment">'--------------------------------------------------------------------------</span>

oPlotLegend.StartAnimationRange 200, 5000, True


<span class="keyword">End Sub</span>


</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
